image: maven:3.3.9-jdk-8
maven-build:
  script: "mvn package -U"
  stage: build
maven-test:
  script: "mvn test"
  stage: test
services:
  - mysql:5.5
stages:
  - test
  - build
variables:
      # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: test
  MYSQL_ROOT_PASSWORD: root
  MYSQL_HOST: mysql:5.5
  MYSQL_USER: root
  MYSQL_PASSWORD: root
# connect:
#   image: mysql
# script:
#   - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE
    