spring:
  data:
    mongodb:
 #     authentication-database:
      #username: chandan
      #password: root
      database: Springdb
      port: 27017
      host: localhost
  application:
    name: category-service
server:
  port: 8083
